server {
  listen 5173;
  root /usr/share/nginx/html;
  index index.html;

  # SPA-роутинг
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Проксирование API на backend
  location /api/ {
    proxy_pass http://kaspi_backend:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
